[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
# Grabbing the the latest 0.6 release canidate, since 0.6 isn't fully released yet
ggez = "0.6.0-rc"
rand = "0.8"
