cargo-features = ["named-profiles", "strip"]

[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times (although it does make debugging shaders a bit more difficult)
debug = 0

[profile.dev-windows]
inherits = "dev"

[profile.release]
opt-level = 3
overflow-checks = false
strip = "symbols"
lto = "fat"
panic = "abort"
debug = 0
codegen-units = 1

[profile.fast-web]
inherits = "dev"
panic = "abort"
overflow-checks = false
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 2

[profile.opt-web]
inherits = "release"
lto = false
codegen-units = 32

[profile.release-web]
inherits = "release"

[profile.fast-web-simd]
inherits = "dev"
panic = "abort"
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 2

[profile.opt-web-simd]
inherits = "release"
lto = false
codegen-units = 32

[profile.release-web-simd]
inherits = "release"


# In order to have Bevy run a little faster, it's compiled with a slightly higher optimization level. This is done instead of optimizing the entire crate in order to have faster build times, while not having the game eat CPU
[profile.dev.package.bevy]
opt-level = 1

[profile.dev.package.bevy_render]
opt-level = 1

[profile.dev.package.bevy_ecs]
opt-level = 1

[profile.dev.package.bevy_app]
opt-level = 1


[dependencies]
# The bevy game engine
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
# Allows for building bevy to the web
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", optional = true }

# A more complex audio library than the one that Bevy uses
bevy_kira_audio = { git = "https://github.com/billyb2/bevy_kira_audio", branch = "bevy_main", features = ["flac"] }

# Using a PR of bevy_networking_turbulence that works with the latest version of Bevy
bevy_networking_turbulence = { git = "https://github.com/smokku/bevy_networking_turbulence", branch = "master", default-features = false, features = ["use-webrtc"] }

# A faster hashmap
hashbrown = { version = "0.11", features = ["nightly"] }

# Logging
wasm-bindgen = { version = "0.2.74", optional = true }

# Used for sending structs over networks easily and efficiently
serde = { version = "1", features = ["derive"] }

#LZ4 is a very fast compression algorithm
lz4_flex = { version = "0.8", default-features = false, features = ["checked-decode", "frame"] }
# CRC32 is a very fast hashing algorithm for verifying files
# Nightly is enabled to do some optimizations
crc32fast = { version = "1", features = ["nightly"] }

# Idk why, but build always fails if winit isn't included as a dep
winit = { version = "0.25.0" }

# Enabling nightly allows using some more optimizations
rand = { version = "0.8", features = ["nightly"] }

[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
  "native",
]

native = [
  "bevy/bevy_wgpu",
  # Since literally every 64 bit CPU has SIMD support, I think it's fine to enable it for rand
  "rand/simd_support",
]

web = [
  "bevy_webgl2",
  "wasm-bindgen",
]

# A patch to get the latest git version of Bevy (with all new features and performance improvements) onto bevy_networking_turbulence
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
# The bevy_* patches are specifically for bevy_networking_turbulence
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy" }

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
target_sdk_version = 29
min_sdk_version = 16
