[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

# Sprite batching will actually slow down the program without some minor optimizations, but is much much faster than drawing normally in optimized programs (especially release builds). Using some minor optimization just so the game runs smoothly

# Check out https://docs.rs/ggez/0.6.0-rc1/ggez/graphics/spritebatch/struct.SpriteBatch.html for more info
[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times
debug = 0
opt-level = 1

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
# Grabbing the the latest 0.6 release canidate, since 0.6 isn't fully released yet
ggez = "0.6.0-rc"
rand = "0.8"
rust-embed= { version = "5" }
game_logic = { path = "game_logic" }
