cargo-features = ["named-profiles"]

[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"
resolver = "2"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times (although it does make debugging shaders a bit more difficult)
debug = 0
opt-level = 0
overflow-checks = false
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.dev-windows]
inherits = "dev"

[profile.release]
opt-level = 3
# You don't need overflow checks if your ints never overflow *taps head*
overflow-checks = false
lto = true
panic = "abort"
debug = 0
codegen-units = 1

[profile.fast-web]
inherits = "dev"
panic = "abort"
overflow-checks = false
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 1

[profile.fast-web.package."*"]
opt-level = 3

[profile.opt-web]
inherits = "release"
# Thin LTO still improves speed, but isn't as slow as fat (true) LTO
lto = "thin"
codegen-units = 32

[profile.release-web]
inherits = "release"

[profile.fast-web-simd]
inherits = "dev"
panic = "abort"
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 2

[profile.opt-web-simd]
inherits = "release"
lto = "thin"
codegen-units = 32

[profile.release-web-simd]
inherits = "release"

[dependencies]
# The bevy game engine
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = ["bevy_winit", "render", "png"] }

# Allows for building bevy to the web
bevy_webgl2 = { git = "https://github.com/billyb2/bevy_webgl2", optional = true }

# A more complex audio library than the one that Bevy uses
#bevy_kira_audio = { git = "https://github.com/billyb2/bevy_kira_audio", branch = "bevy_main", features = ["flac"] }

# Networking library
#bevy_networking_turbulence = { version = "0.3", default-features = false, features = ["use-webrtc"] }
bevy_networking_turbulence = { git = "https://github.com/billyb2/bevy_networking_turbulence", default-features = false, features = ["use-webrtc"] }

# WASM logging
wasm-bindgen = { version = "0.2.74", optional = true }

# Used for sending structs over networks easily and efficiently
serde = { version = "1", features = ["derive"] }

#LZ4 is a very fast compression algorithm
lz4_flex = { version = "0.8", default-features = false, features = ["checked-decode", "frame"] }

# CRC32 is a very fast hashing algorithm for verifying files
# Nightly is enabled to do some optimizations
crc32fast = { version = "1", features = ["nightly"] }

# Idk why, but build always fails if winit isn't included as a dep
winit = { version = "0.25.0" }

# Enabling nightly allows using some more optimizations
rand = { version = "0.8", features = ["nightly"] }

# Enables running very slow tasks in parallel
rayon = { version = "1", optional = true }

# Allows global variables 
lazy_static = { version = "1" }

# A hashmap that's very fast at storing singular bytes as keys (made by me)
single_byte_hashmap = { version = "0.1", features = ["nightly"] }

# Just a regular HashMap
hashbrown = { version = "0.11", features = ["rayon", "nightly"] }
rustc-hash = { version = "1" }

# Easy SIMD
core_simd = { git = "https://github.com/rust-lang/portable-simd" }


[features]
default = [
  "native",
]

native = [
  "bevy/bevy_wgpu",
  # Since literally every 64 bit CPU has 128-bit SIMD support, I think it's fine to enable it for rand
  "rand/simd_support",
  "parallel",
]

parallel = [
  "rayon",
  "single_byte_hashmap/rayon",
]

web = [
  "bevy_webgl2",
  "wasm-bindgen",
]

# A patch to get the latest git version of Bevy (with all new features and performance improvements) onto bevy_networking_turbulence
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
# The bevy_* patches are specifically for bevy_networking_turbulence
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy" }
bevy_core = { git = "https://github.com/bevyengine/bevy" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
