cargo-features = ["named-profiles"]

[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times
debug = 0
# Bevy currently doesn't support 2d sprite batching, which is horrific, so I need to use a slightly higher optimization level
opt-level = 1

[profile.dev-windows]
inherits = "dev"

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.fast-web]
inherits = "dev"
panic = "abort"
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 2

[profile.opt-web]
inherits = "release"
lto = false
codegen-units = 32

[profile.release-web]
inherits = "release"

[profile.fast-web-simd]
inherits = "dev"
panic = "abort"
# Since web builds run like garbage, using a higher optimization level is nice
opt-level = 2

[profile.opt-web-simd]
inherits = "release"
lto = false
codegen-units = 32

[profile.release-web-simd]
inherits = "release"

[dependencies]
# The bevy game engine
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
# Allows for building bevy to the web
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", optional=true }
# Using a PR of bevy_networking_turbulence that works with the latest version of Bevy
bevy_networking_turbulence = { git = "https://github.com/smokku/bevy_networking_turbulence", branch = "master", default-features = false, features = ["use-webrtc"] }

# Logging
wasm-bindgen = { version = "0.2.74", optional = true }

# Used for sending structs over networks easily and efficiently
serde = { version = "1", features = ["derive"] }

#LZ4 is a very fast compression algorithm
lz4_flex = { version = "0.8", default-features = false, features = ["checked-decode", "frame"] }
# CRC32 is a very fast hashing algorithm for verifying files
crc32fast = { version = "1", features = ["nightly"] }

# Gotta use an older version of winit
winit = { version = "0.24.0" }
# Enabling nightly allows using some more optimizations
rand = { version = "0.8", features = ["nightly"] }


[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png"
]

native = [
  "bevy/bevy_wgpu",
  # Since literally every modern CPU has SIMD support, I think it's fine to enable it for rand
  "rand/simd_support",
]

web = [
  "bevy_webgl2",
  "wasm-bindgen",
]

# A patch to get the latest git version of Bevy (with all new features and performance improvements) onto bevy_networking_turbulence
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
# The bevy_* patches are specifically for bevy_networking_turbulence
bevy_ecs = { git = "https://github.com/bevyengine/bevy", default-features = false }
bevy_app = { git = "https://github.com/bevyengine/bevy", default-features = false }
bevy_tasks = { git = "https://github.com/bevyengine/bevy", default-features = false }

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
target_sdk_version = 29
min_sdk_version = 16
