[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times
debug = 0
# Bevy currently doesn't support 2d sprite batching, which is horrific, so I need to use a higher optimization level than I'd like
opt-level = 1

# Optimizing every package highly, so higher clean build times but also higher performance
[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
bevy = {version = "0.5", default-features=false}
bevy_webgl2 = {version = "0.5"  , optional=true}
# Unlinke the rand crate, get_random supports every target under the sun, inclulding WASM and iOS which rand doesn't support easily
# All targets: https://docs.rs/getrandom/0.2.2/getrandom/
# getrandom = { version = "0.2", features=["wasm-bindgen"]}
# Using a pull request of lz4_flex that supports frame (de)compression, since currently lz4_flex does not
lz4_flex = { git = "https://github.com/arthurprs/lz4_flex", branch = "dict", default-features = false, features = ["checked-decode", "std"] }
crc32fast = "1"
# TODO: Use Bevy tilemap for sprite batching on maps

# Gotta use an older version of winit and rand for the web build to work
winit = {version = "0.24.0"}

#Other platform stuff:
[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
]

native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2"
]

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
target_sdk_version = 29
min_sdk_version = 16

