[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times
debug = 0
# Bevy currently doesn't support 2d sprite batching, which is horrific, so I need to use a higher optimization level than I'd like
opt-level = 1

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "4a477e762dbe881430385559456b4140881b6f92", default-features = false }
bevy_webgl2 = { version = "0.5", optional=true }
# Using a pull request of lz4_flex that supports frame (de)compression, since currently the main lz4_flex does not
lz4_flex = { git = "https://github.com/arthurprs/lz4_flex", branch = "dict", default-features = false, features = ["checked-decode", "std"] }
crc32fast = "1"
# Gotta use an older version of winit and rand for the web build to work
winit = { version = "0.24.0" }

# This is a fix for rand to work on WASM
# rand = "0.8"
# getrandom = { version="0.1", features=["wasm-bindgen"] }

#Other platform stuff:
[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
]

native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2",
]

# A patch to force bevy_webgl2 to use the latest version of Bevy
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "4a477e762dbe881430385559456b4140881b6f92", default-features = false }

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
target_sdk_version = 29
min_sdk_version = 16

