cargo-features = ["named-profiles"]

[package]
name = "game"
version = "0.1.0"
authors = ["William Batista <bootlegbilly@protonmail.ch>", "Luke Gaston <lsgaston@myhoosierneighbors.com>"]
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times
debug = 0
# Bevy currently doesn't support 2d sprite batching, which is horrific, so I need to use a slightly higher optimization level
opt-level = 1

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.fast-web]
inherits = "dev"

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_webgl2 = { version = "0.5", optional=true }
# Using a PR of bevy_networking_turbulence that works with the latest version of Bevy
bevy_networking_turbulence = { git = "https://github.com/phuoc-thanh/bevy_networking_turbulence", branch = "dev", default-features = false, features = ["use-webrtc"] }

# Logging
console_log = { version = "0.2", optional = true }
log = { version = "0.4" }
console_error_panic_hook = { version = "0.1", optional = true }

# Using a pull request of lz4_flex that supports frame (de)compression, since currently the main lz4_flex does not
lz4_flex = { git = "https://github.com/arthurprs/lz4_flex", branch = "dict", default-features = false, features = ["checked-decode", "std", "frame"] }
crc32fast = "1"

# Gotta use an older version of winit
winit = { version = "0.24.0" }
rand = { version = "0.8" }


#Other platform stuff:
[features]
default = [
  "bevy/bevy_winit",
  "bevy/render",
]

native = [
  "bevy/bevy_wgpu",
  # Since literally every modern CPU has SIMD support, I think it's fine to enable it for rand
  # For WASM, however, SIMD support is currently behind a feature flag for Firefox, and older versions of Chrome don't have it at all, so we should definetly just use SIMD for PC
  "rand/simd_support",
]

web = [
  "bevy_webgl2",
  "console_log",
  "console_error_panic_hook",
]

# A patch to get the latest git version of Bevy (with all new features and performance improvements) onto bevy_webgl2
# Currently disabled since bevy_networking_turbulence needs bevy 0.5
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
# The bevy_* patches are specifically for bevy_networking_turbulence
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy" }

naia-client-socket = { path = "deps/naia-socket/client" }
naia-server-socket = { path = "deps/naia-socket/server" }

[package.metadata.android]
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
target_sdk_version = 29
min_sdk_version = 16

