[env]
CARGO_TARGET_DIR = {value = "target", condition = {env_not_set = ["CARGO_TARGET_DIR"]}}
CARGO_WASM_PATH = "${CARGO_TARGET_DIR}/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm"
CARGO_PROFILE = "dev"
TARGET_DIR = "target"
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[tasks.show-env]
command = "env"

[tasks.install-target-wasm32-unknown-unknown]
args = ["target", "install", "wasm32-unknown-unknown"]
command = "rustup"

[tasks.basic-http-server]
install_crate = {crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help"}

[tasks.wasm-bindgen-cli]
#Gotta install a slightly older verson of wasm-bindgen-cli
install_crate = {crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help", version = "0.2.69"}

[tasks.cargo-build-web]
args = ["build", "--target", "wasm32-unknown-unknown", "--features", "web", "--release"]
command = "cargo"
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.cargo-build-web-debug]
args = ["build", "--target", "wasm32-unknown-unknown", "--features", "web"]
command = "cargo"
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.build-web]
args = ["--out-dir", "${TARGET_DIR}", "--out-name", "wasm", "--target", "web", "${CARGO_WASM_PATH}"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web", "wasm-bindgen-cli"]

[tasks.build-web-debug]
args = ["--out-dir", "${TARGET_DIR}", "--out-name", "wasm", "--target", "web", "${CARGO_WASM_PATH}"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web-debug", "wasm-bindgen-cli"]

[tasks.build-native]
args = ["build", "--features", "native"]
command = "cargo"

[tasks.build-native-release]
args = ["build", "--features", "native", "--release"]
command = "cargo"

[tasks.build-native-fast]
args = ["build", "--features", "native", "--features", "bevy/dynamic"]
command = "cargo"

[tasks.run]
args = ["run", "--features", "native", "--features", "bevy/dynamic"]
command = "cargo"

[tasks.run-release]
command = "${CARGO_TARGET_DIR}/release/${CARGO_MAKE_BINARY_EXECUTABLE_NAME}"
dependencies = ["build-native-release"]

[tasks.serve]
command = "basic-http-server"
dependencies = ["build-web", "basic-http-server"]

[tasks.check-native]
args = ["clippy", "--features", "native", "--", "-D", "warnings"]
command = "cargo"

[tasks.check-web]
args = ["clippy", "--features", "web", "--target", "wasm32-unknown-unknown", "--", "-D", "warnings"]
command = "cargo"

[tasks.check]
dependencies = ["check-web", "check-native"]

[tasks.serve-debug]
command = "basic-http-server"
dependencies = ["build-web-debug", "basic-http-server"]
