[package]
name = "aggro_bot"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 0
lto = "fat"
panic = "abort"
codegen-units = 1

[lib]
crate-type = ["cdylib"]

[dependencies]
glam = "0.20"

