[package]
name = "game_types"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", features = ["nightly"] }
