[package]
name = "game_types"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", features = ["nightly"] }
