[package]
name = "ui_graphics"
version = "0.1.0"
edition = "2021"
crate-type = ["rlib", "dylib"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
serde = { version = "1", features = ["derive"] }
arrayvec = { version = "0.7" }
