version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/rust
    environment:
      # Fail the build if there are warnings
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      - run:
          name: Installing prerequisites
          command: rustup install nightly && rustup default nightly && sudo apt-get install libasound2-dev libudev-dev pkg-config lld clang mesa-vulkan-drivers -y && rustup target add wasm32-unknown-unknown --toolchain nightly
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build for PC
          command: cargo build --features native
      - run:
          name: Verify it will compile to Web Assembly
          command: cargo check --features web --target wasm32-unknown-unknown

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/wasm32-unknown-unknown/release/.fingerprint
            - target/wasm32-unknown-unknown/release/build
            - target/wasm32-unknown-unknown/release/deps
            - target/wasm32-unknown-unknown/debug/.fingerprint
            - target/wasm32-unknown-unknown/debug/build
            - target/wasm32-unknown-unknown/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

  security:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Cache permission
          command: |
            sudo chown -R $(whoami):$(id -ng) /usr/local/cargo

  lint:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Install prerequisites
          command: rustup install nightly && rustup default nightly && sudo apt-get install libasound2-dev libudev-dev pkg-config lld clang mesa-vulkan-drivers -y && rustup target add wasm32-unknown-unknown --toolchain nightly
      - run:
          name: Linting
          command: cargo clippy -- -D warnings

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - security:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/

