#[build]
#jobs = 1

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
# The enabled target features are included in most modern CPU's
# 	They basically just enable CPU instructions that should make the game run much faster
#	In production, we should have an installer that detects which CPU features are available, and download different binaries depending on the features
# 	Once compilation on Windows works, we should do the same for it

# Stripping symbols is done to significantly reduce the binary size
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y", "-Ctarget-cpu=x86-64-v3", "-Zstrip=symbols", "-Cprefer-dynamic"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y", "-Zstrip=symbols", "-Csplit-debuginfo=unpacked"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n", "-Zstrip=symbols"]


[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y", "-Zstrip=symbols", "-Ctarget-cpu=native"]
