#[build]
#jobs = 1

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
# The enabled target features are included in every CPU since 2008 for Intel and 2011 for AMD
# Once compilation on Windows works, we should do the same for it
# Stripping symbols is done to significantly reduce the binary size
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y", "-Zstrip=symbols", "-Ctarget-feature=+sse3,+avx"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=/usr/local/bin/zld", "-Zshare-generics=y", "-Zstrip=symbols", "-Csplit-debuginfo=unpacked"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=false", "-Zstrip=symbols"]
