[package]
name = "compress_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
brotli = "3"

[profile.release]
opt-level = 3
overflow-checks = false
lto = "fat"
panic = "abort"
debug = 0
codegen-units = 1
