[package]
name = "tcp_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "io-util"] }

bincode = { version = "1" }
serde = { version = "1" }
arrayvec = { version = "0.7" }
dashmap = { version = "4", features = ["rayon"] }
